export const products = [
  {
    id: "prod-001",
    name: "Velvet Cream Sofa",
    price: 999.99,
    category: "sofa",
    image: "img/sofa-velvet-cream.jpg",
    description: "Luxurious velvet sofa with modern design",
  },
  {
    id: "prod-002",
    name: "Leather Cream Sofa",
    price: 1299.99,
    category: "sofa",
    image: "img/sofa-leather-cream.jpg",
    description: "Premium leather sofa with elegant design",
  },
  {
    id: "prod-003",
    name: "Oak Cream Sofa",
    price: 899.99,
    category: "sofa",
    image: "img/sofa-oak-cream.jpg",
    description: "Classic oak sofa with comfortable cushions",
  },
  {
    id: "prod-004",
    name: "Velvet Cream Chair",
    price: 299.99,
    category: "chair",
    image: "img/chair-velvet-cream.jpg",
    description: "Elegant velvet chair for your living room",
  },
  {
    id: "prod-005",
    name: "Leather Cream Chair",
    price: 399.99,
    category: "chair",
    image: "img/chair-leather-cream.jpg",
    description: "Premium leather chair with modern design",
  },
  {
    id: "prod-006",
    name: "Oak Cream Chair",
    price: 349.99,
    category: "chair",
    image: "img/chair-oak-cream.jpg",
    description: "Classic oak chair with comfortable cushion",
  },
  {
    id: "prod-007",
    name: "Velvet Cream Table",
    price: 499.99,
    category: "table",
    image: "img/table-velvet-cream.jpg",
    description: "Stylish velvet table with modern design",
  },
  {
    id: "prod-008",
    name: "Leather Cream Table",
    price: 599.99,
    category: "table",
    image: "img/table-leather-cream.webp",
    description: "Premium leather table with elegant design",
  },
  {
    id: "prod-009",
    name: "Oak Cream Table",
    price: 449.99,
    category: "table",
    image: "img/table-oak-cream.webp",
    description: "Classic oak table with modern design",
  },
  {
    id: "prod-010",
    name: "Velvet Cream Dining Set",
    price: 1599.99,
    category: "dining",
    image: "img/dining-velvet-cream.webp",
    description: "Complete velvet dining set for your family",
  },
  {
    id: "prod-011",
    name: "Leather Cream Dining Set",
    price: 1799.99,
    category: "dining",
    image: "img/dining-leather-cream.jpg",
    description: "Premium leather dining set with elegant design",
  },
  {
    id: "prod-012",
    name: "Oak Cream Dining Set",
    price: 1499.99,
    category: "dining",
    image: "img/dining-oak-cream.avif",
    description: "Classic oak dining set for your home",
  },
  {
    id: "prod-013",
    name: "Velvet Gray Sofa",
    price: 1099.99,
    category: "sofa",
    image: "img/sofa-velvet-taupe.jpg",
    description: "Modern gray velvet sofa with elegant design",
  },
  {
    id: "prod-014",
    name: "Leather Gray Sofa",
    price: 1399.99,
    category: "sofa",
    image: "img/sofa-leather-gray.jpg",
    description: "Premium gray leather sofa with modern design",
  },
  {
    id: "prod-015",
    name: "Oak Gray Sofa",
    price: 999.99,
    category: "sofa",
    image: "img/sofa-oak-gray.avif",
    description: "Classic gray oak sofa with comfortable cushions",
  },
  {
    id: "prod-016",
    name: "Velvet Gray Chair",
    price: 349.99,
    category: "chair",
    image: "img/chair-velvet-gray.jpg",
    description: "Elegant gray velvet chair for your living room",
  },
  {
    id: "prod-017",
    name: "Leather Gray Chair",
    price: 449.99,
    category: "chair",
    image: "img/chair-leather-gray.jpg",
    description: "Premium gray leather chair with modern design",
  },
  {
    id: "prod-018",
    name: "Oak Gray Chair",
    price: 399.99,
    category: "chair",
    image: "img/chair-oak-gray.jpg",
    description: "Classic gray oak chair with comfortable cushion",
  },
  {
    id: "prod-019",
    name: "Velvet Gray Table",
    price: 549.99,
    category: "table",
    image: "img/table-velvet-gray.jpg",
    description: "Stylish gray velvet table with modern design",
  },
  {
    id: "prod-020",
    name: "Leather Gray Table",
    price: 649.99,
    category: "table",
    image: "img/table-leather-gray.avif",
    description: "Premium gray leather table with elegant design",
  },
  {
    id: "prod-021",
    name: "Oak Gray Table",
    price: 499.99,
    category: "table",
    image: "img/table-oak-gray.jpg",
    description: "Classic gray oak table with modern design",
  },
  {
    id: "prod-022",
    name: "Velvet Gray Dining Set",
    price: 1699.99,
    category: "dining",
    image: "img/dining-velvet-gray.webp",
    description: "Complete gray velvet dining set for your family",
  },
  {
    id: "prod-023",
    name: "Leather Gray Dining Set",
    price: 1899.99,
    category: "dining",
    image: "img/dining-leather-gray.jpg",
    description: "Premium gray leather dining set with elegant design",
  },
  {
    id: "prod-024",
    name: "Oak Gray Dining Set",
    price: 1599.99,
    category: "dining",
    image: "img/dining-oak-gray.webp",
    description: "Classic gray oak dining set for your home",
  },
  {
    id: "prod-025",
    name: "Rustic Oak Coffee Table",
    price: 349.0,
    category: "tables",
    image: "img/table-leather-cream.webp",
    description: "Handcrafted oak coffee table with rustic finish",
  },
  {
    id: "prod-026",
    name: "Minimalist Dining Chair",
    price: 199.99,
    category: "chairs",
    image: "img/Minimalist Dining Chair.webp",
    description: "Clean and simple dining chair design",
  },
  {
    id: "prod-027",
    name: "Modern Sectional Sofa",
    price: 1299.99,
    category: "sofas",
    image: "img/Modern Sectional Sofa.jpg",
    description: "Versatile sectional sofa with chaise lounge",
  },
  {
    id: "prod-028",
    name: "Industrial Dining Table",
    price: 799.99,
    category: "tables",
    image: "img/Industrial Dining Table.jpg",
    description: "Sturdy industrial-style dining table with metal accents",
  },
  {
    id: "prod-029",
    name: "Ergonomic Office Chair",
    price: 299.99,
    category: "chairs",
    image: "img/Ergonomic Office Chair.webp",
    description: "Comfortable office chair with lumbar support",
  },
  {
    id: "prod-030",
    name: "Velvet Chesterfield Sofa",
    price: 1499.99,
    category: "sofas",
    image: "img/Velvet Chesterfield Sofa.jpg",
    description: "Classic Chesterfield sofa with premium velvet upholstery",
  },
  {
    id: "prod-031",
    name: "Glass Side Table",
    price: 249.99,
    category: "tables",
    image: "img/Glass Side Table.jpg",
    description: "Modern glass side table with metal frame",
  },
  {
    id: "prod-032",
    name: "Wingback Accent Chair",
    price: 599.99,
    category: "chairs",
    image: "img/Wingback Accent Chair.webp",
    description: "Elegant wingback chair with tufted backrest",
  },
  {
    id: "prod-033",
    name: "L-Shape Corner Sofa",
    price: 1899.99,
    category: "sofas",
    image: "img/L-Shape Corner Sofa.webp",
    description: "Spacious L-shaped sofa with storage compartments",
  },
  {
    id: "prod-034",
    name: "Marble Console Table",
    price: 449.99,
    category: "tables",
    image: "img/Marble Console Table.webp",
    description: "Luxurious marble console table with gold accents",
  },
  {
    id: "prod-035",
    name: "Modern Accent Chair",
    price: 399.99,
    category: "chairs",
    image: "img/Modern Accent Chair.jpg",
    description: "Contemporary accent chair with geometric design",
  },
  {
    id: "prod-036",
    name: "Reclining Sofa",
    price: 1599.99,
    category: "sofas",
    image: "img/Reclining Sofa.webp",
    description: "Power reclining sofa with USB ports and cup holders",
  },
  {
    id: "prod-037",
    name: "Glass Dining Table",
    price: 599.99,
    category: "tables",
    image: "img/Glass Dining Table.jpg",
    description: "Modern glass dining table with chrome base",
  },
  {
    id: "prod-038",
    name: "Office Desk Chair",
    price: 249.99,
    category: "chairs",
    image: "img/Office Desk Chair.webp",
    description: "Ergonomic office chair with adjustable height",
  },
  {
    id: "prod-039",
    name: "Luxury Sectional",
    price: 2499.99,
    category: "sofas",
    image: "img/Luxury Sectional.jpg",
    description: "Premium leather sectional with power headrests",
  },
  {
    id: "prod-040",
    name: "Coffee Table Set",
    price: 449.99,
    category: "tables",
    image: "img/Coffee Table Set.webp",
    description: "Set of 3 nesting coffee tables with marble tops",
  },
  {
    id: "prod-041",
    name: "Modern Coffee Table",
    price: 499.99,
    category: "tables",
    image: "img/Modern Coffee Table.webp",
    description: "Stylish modern coffee table with glass top",
  },
  {
    id: "prod-042",
    name: "Rustic Coffee Table",
    price: 399.99,
    category: "tables",
    image: "img/Rustic Coffee Table.webp",
    description: "Rustic wooden coffee table with storage",
  },
  {
    id: "prod-043",
    name: "Verona Leather Armchair",
    price: 899.0,
    description:
      "Elegant and comfortable leather armchair with premium craftsmanship",
    image: "img/Verona Leather Armchair.jpg",
    category: "Living Room",
    materials: ["Leather", "Wood"],
    colors: ["Gray", "Brown", "Black"],
    dimensions: {
      width: 75,
      height: 85,
      depth: 80,
    },
  },
  {
    id: "prod-044",
    name: "Rustic Oak Coffee Table",
    price: 349.0,
    description: "Beautiful rustic coffee table made from solid oak wood",
    image: "img/table-oak-cream.webp",
    category: "Living Room",
    materials: ["Oak", "Wood"],
    colors: ["Cream", "Natural"],
    dimensions: {
      width: 120,
      height: 45,
      depth: 60,
    },
  },
  {
    id: "prod-045",
    name: "Bohemian Sectional Sofa",
    price: 1199.0,
    description:
      "Spacious and stylish sectional sofa with modern bohemian design",
    image: "img/Bohemian Sectional Sofa.jpg",
    category: "Living Room",
    materials: ["Fabric", "Wood"],
    colors: ["Beige", "Gray", "Blue"],
    dimensions: {
      width: 280,
      height: 85,
      depth: 170,
    },
  },
  {
    id: "prod-046",
    name: "Velvet Bed Frame",
    price: 1299.0,
    description: "Luxurious velvet bed frame with elegant tufted headboard",
    image: "img/Velvet Bed Frame.jpg",
    category: "Bedroom",
    materials: ["Velvet", "Wood"],
    colors: ["Gray", "Blue", "Pink"],
    dimensions: {
      width: 160,
      height: 120,
      depth: 200,
    },
  },
];
